import {createHash} from "node:crypto";import OpenAI from "openai";import {COMPANION_SERVICES} from "../data/companionServices.js";
const model=process.env.OPENAI_MODEL||"gpt-5.6-sol";const tokens=(value)=>new Set(String(value||"").toLowerCase().match(/[a-z0-9-]+/g)||[]);
const score=(service,answers)=>{let value=0;if(service.domains.includes(answers.domain))value+=12;if(service.goals.includes(answers.goal))value+=7;if(service.lifeStages.includes(answers.lifeStage))value+=3;const words=tokens(answers.description);for(const keyword of service.keywords){if([...tokens(keyword)].some((word)=>words.has(word)))value+=4;}if(answers.domain==="not-sure")value+=1;return value;};
const nextSteps=(service)=>["Review the service boundary and the recommended pathway.","Open the task-specific journey and answer only the minimum required questions.","Complete sensitive or official transactions only with the responsible provider or authority."];
export const deterministicRecommendations=(answers)=>COMPANION_SERVICES.map((service)=>({service,score:score(service,answers)})).sort((a,b)=>b.score-a.score||a.service.title.localeCompare(b.service.title)).slice(0,3).map(({service,score:points},index)=>({serviceCode:service.serviceCode,title:service.title,route:service.route,summary:service.summary,why:index===0?`Best match for your ${answers.goal.replaceAll("-"," ")} goal and ${answers.domain.replaceAll("-"," ")} topic.`:`Another relevant route based on your goal, life stage and description.`,confidence:points>=15?"high":points>=7?"medium":"low",boundary:service.boundary,nextSteps:nextSteps(service)}));
const schema={type:"object",properties:{recommendations:{type:"array",minItems:1,maxItems:3,items:{type:"object",properties:{serviceCode:{type:"string"},why:{type:"string"},confidence:{type:"string",enum:["low","medium","high"]}},required:["serviceCode","why","confidence"],additionalProperties:false}}},required:["recommendations"],additionalProperties:false};
const safetyIdentifier=(userId)=>createHash("sha256").update(`vidhya-companion:${userId}`).digest("hex");
const enhance=async(answers,candidates,userId)=>{if(!process.env.OPENAI_API_KEY)return null;try{const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model,reasoning:{effort:"low"},safety_identifier:safetyIdentifier(userId),instructions:"Rank only the supplied Vidhya Vedha services. Never decide eligibility or invent a service, deadline, fee, status, benefit, provider or official rule. Explain the fit in plain language. Return structured data only.",input:JSON.stringify({answers,candidates:candidates.map(({serviceCode,title,summary,boundary})=>({serviceCode,title,summary,boundary}))}),text:{format:{type:"json_schema",name:"companion_recommendations",strict:true,schema}}});const parsed=JSON.parse(response.output_text);const byCode=new Map(candidates.map((item)=>[item.serviceCode,item]));const safe=parsed.recommendations.map((item)=>byCode.has(item.serviceCode)?{...byCode.get(item.serviceCode),why:item.why,confidence:item.confidence}:null).filter(Boolean);return safe.length?{recommendations:safe,mode:"openai",model}:null;}catch(error){console.error("Companion recommendation fallback:",error?.message||error);return null;}};
export const recommendServices=async({answers,userId})=>{const fallback=deterministicRecommendations(answers);const generated=await enhance(answers,fallback,userId);return generated||{recommendations:fallback,mode:"reviewed-rules",model:null};};
