import { STATUS_PROVIDERS } from "../data/statusProviders.js";
import StatusTracker from "../models/StatusTracker.js";
import { readProviderStatus } from "../services/statusConnectorService.js";
const output = (item) => ({ trackerId:item.trackerId,providerCode:item.providerCode,targetId:item.targetId,label:item.label,connector:item.connector,currentStatus:item.currentStatus,statusMessage:item.statusMessage,sourceUpdatedAt:item.sourceUpdatedAt,lastCheckedAt:item.lastCheckedAt,status:item.status,createdAt:item.createdAt,updatedAt:item.updatedAt });
export const listStatusProviders=(_req,res)=>res.json({providers:STATUS_PROVIDERS});
export const createStatusTracker=async(req,res)=>{const result=await readProviderStatus({...req.body,userId:req.user.userId});if(!result)return res.status(404).json({error:"Owned service record was not found."});const item=await StatusTracker.create({userId:req.user.userId,providerCode:req.body.providerCode,targetId:req.body.targetId,label:result.provider.label,connector:result.connector,currentStatus:result.currentStatus,statusMessage:result.statusMessage,sourceUpdatedAt:result.sourceUpdatedAt,lastCheckedAt:new Date()});return res.status(201).json({message:result.connector==="not-connected"?"Tracker saved, but no verified official API is connected.":"Status tracker connected.",tracker:output(item)});};
export const listMyStatusTrackers=async(req,res)=>{const items=await StatusTracker.find({userId:req.user.userId}).sort({createdAt:-1}).limit(50);return res.json({trackers:items.map(output)});};
export const refreshStatusTracker=async(req,res)=>{const item=await StatusTracker.findOne({trackerId:req.params.trackerId,userId:req.user.userId,status:"active"});if(!item)return res.status(404).json({error:"Active tracker not found."});const result=await readProviderStatus({providerCode:item.providerCode,targetId:item.targetId,userId:req.user.userId});if(!result)return res.status(404).json({error:"Owned service record is no longer available."});Object.assign(item,{connector:result.connector,currentStatus:result.currentStatus,statusMessage:result.statusMessage,sourceUpdatedAt:result.sourceUpdatedAt,lastCheckedAt:new Date()});await item.save();return res.json({message:"Status source checked.",tracker:output(item)});};
export const archiveStatusTracker=async(req,res)=>{const item=await StatusTracker.findOne({trackerId:req.params.trackerId,userId:req.user.userId});if(!item)return res.status(404).json({error:"Tracker not found."});item.status="archived";item.archivedAt=new Date();await item.save();return res.json({message:"Tracker archived.",tracker:output(item)});};
