import React from "react";import {fireEvent,render,screen,waitFor} from "@testing-library/react";import {MemoryRouter} from "react-router-dom";import {beforeEach,describe,expect,it,vi} from "vitest";import Ecommerce from "./Ecommerce.jsx";import api from "../../services/api.js";import {useAuth} from "../../context/AuthContext.jsx";
vi.mock("../../services/api.js",()=>({default:{get:vi.fn(),post:vi.fn(),patch:vi.fn()}}));vi.mock("../../context/AuthContext.jsx",()=>({useAuth:vi.fn()}));
const guide={guideCode:"marketplace-refund",category:"orders",title:"Non-delivery, return or refund problem",authority:"National Consumer Helpline",officialUrl:"https://consumerhelpline.gov.in/",summary:"Ask the marketplace for a remedy.",boundary:"Do not share payment credentials.",tasks:[{taskId:"contact-platform",title:"Contact official platform support",description:"Use official support."}]};const item={caseId:"COM-12AB34CD",guideCode:guide.guideCode,guideTitle:guide.title,officialUrl:guide.officialUrl,merchantLabel:"Marketplace A",orderLabel:"ending 1234",incidentDate:"2026-07-20",desiredOutcome:"refund",status:"open",tasks:guide.tasks.map((task)=>({...task,status:"not-started"}))};
const configure=(cases=[])=>{api.get.mockImplementation((url)=>url.endsWith("/guides")?Promise.resolve({data:{guides:[guide]}}):Promise.resolve({data:{cases}}));api.post.mockResolvedValue({data:{case:item}});api.patch.mockImplementation((url,payload)=>Promise.resolve({data:{case:url.includes("/tasks/")?{...item,tasks:[{...item.tasks[0],status:"completed"}]}:{...item,status:payload.status}}}));};const renderPage=()=>render(<MemoryRouter><Ecommerce/></MemoryRouter>);
describe("Ecommerce resolution workspace",()=>{beforeEach(()=>{vi.clearAllMocks();configure();});
 it("shows an official route and no payment, account, address, or OTP forms",async()=>{useAuth.mockReturnValue({user:null});renderPage();expect(await screen.findByRole("heading",{name:guide.title})).toBeInTheDocument();expect(screen.getByRole("link",{name:/official resolution route/i})).toHaveAttribute("href",guide.officialUrl);expect(screen.queryByLabelText(/amount|account id|pickup address|mobile number|otp|upi pin/i)).not.toBeInTheDocument();expect(screen.queryByText(/submit request/i)).not.toBeInTheDocument();});
 it("creates a minimal-data resolution case",async()=>{useAuth.mockReturnValue({user:{name:"Leela"}});renderPage();await screen.findByRole("heading",{name:guide.title});fireEvent.change(screen.getByLabelText(/seller or carrier label/i),{target:{value:"Marketplace A"}});fireEvent.change(screen.getByLabelText(/short order reference/i),{target:{value:"ending 1234"}});fireEvent.change(screen.getByLabelText(/incident date/i),{target:{value:"2026-07-20"}});fireEvent.click(screen.getByRole("button",{name:/create resolution case/i}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/ecommerce/cases",{guideCode:guide.guideCode,merchantLabel:"Marketplace A",orderLabel:"ending 1234",incidentDate:"2026-07-20",desiredOutcome:"refund"}));expect(JSON.stringify(api.post.mock.calls[0][1])).not.toMatch(/amount|address|account|card|otp|evidence/i);});
 it("tracks a task and resolves a case",async()=>{useAuth.mockReturnValue({user:{name:"Leela"}});configure([item]);renderPage();fireEvent.click(await screen.findByRole("button",{name:/my resolution cases/i}));fireEvent.click(screen.getByLabelText(/contact official platform support/i));await waitFor(()=>expect(api.patch).toHaveBeenCalledWith("/ecommerce/cases/COM-12AB34CD/tasks/contact-platform",{completed:true}));fireEvent.click(screen.getByRole("button",{name:/mark resolved/i}));await waitFor(()=>expect(api.patch).toHaveBeenCalledWith("/ecommerce/cases/COM-12AB34CD/status",{status:"resolved"}));});
});
