import React,{useEffect,useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {useAuth} from "../../context/AuthContext.jsx";
import api from "../../services/api.js";
import "./Ecommerce.css";
const today=()=>new Date().toISOString().slice(0,10);
const outcomeLabels={refund:"Refund",replacement:"Replacement",delivery:"Delivery", "charge-review":"Charge review",information:"Information or explanation"};
function Ecommerce(){
 const {user}=useAuth(); const [guides,setGuides]=useState([]); const [cases,setCases]=useState([]); const [selectedCode,setSelectedCode]=useState(""); const [view,setView]=useState("guides"); const [query,setQuery]=useState(""); const [merchantLabel,setMerchantLabel]=useState(""); const [orderLabel,setOrderLabel]=useState(""); const [incidentDate,setIncidentDate]=useState(today()); const [desiredOutcome,setDesiredOutcome]=useState("refund"); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const requests=[api.get("/ecommerce/guides")];if(user)requests.push(api.get("/ecommerce/cases/mine"));const [guideResponse,caseResponse]=await Promise.all(requests);setGuides(guideResponse.data.guides);setSelectedCode(guideResponse.data.guides[0]?.guideCode||"");setCases(caseResponse?.data?.cases||[]);}catch(err){setError(err.response?.data?.error||"Consumer guidance could not be loaded.");}})();},[user]);
 const selected=guides.find(({guideCode})=>guideCode===selectedCode); const filtered=useMemo(()=>{const text=query.trim().toLowerCase();return text?guides.filter((guide)=>JSON.stringify(guide).toLowerCase().includes(text)):guides;},[guides,query]); const activeCases=cases.filter(({status})=>status!=="archived");
 const createCase=async()=>{if(!selected)return;setBusy(true);setError("");try{const {data}=await api.post("/ecommerce/cases",{guideCode:selected.guideCode,merchantLabel,orderLabel,incidentDate,desiredOutcome});setCases((current)=>[data.case,...current]);setNotice(`Case ${data.case.caseId} is ready. Evidence and payment credentials were not stored.`);setView("cases");}catch(err){setError(err.response?.data?.error||"The resolution case could not be created.");}finally{setBusy(false);}};
 const updateTask=async(item,task,completed)=>{setBusy(true);try{const {data}=await api.patch(`/ecommerce/cases/${item.caseId}/tasks/${task.taskId}`,{completed});setCases((current)=>current.map((entry)=>entry.caseId===data.case.caseId?data.case:entry));}catch(err){setError(err.response?.data?.error||"Progress could not be updated.");}finally{setBusy(false);}};
 const setStatus=async(caseId,status)=>{setBusy(true);try{const {data}=await api.patch(`/ecommerce/cases/${caseId}/status`,{status});setCases((current)=>current.map((entry)=>entry.caseId===data.case.caseId?data.case:entry));setNotice(`${caseId} marked ${status}.`);}catch(err){setError(err.response?.data?.error||"Case status could not be updated.");}finally{setBusy(false);}};
 return <main className="commerce-page"><header className="commerce-hero"><div className="commerce-shell"><p className="commerce-kicker">Consumer resolution workspace</p><h1>Resolve an order, payment or delivery problem safely</h1><p>Use reviewed official routes, keep evidence private, and track the next action without sharing payment credentials, full addresses or account access.</p></div></header>
 <nav className="commerce-tabs commerce-shell" aria-label="Commerce workspace"><button type="button" aria-current={view==="guides"?"page":undefined} onClick={()=>setView("guides")}>Find a resolution route</button><button type="button" aria-current={view==="cases"?"page":undefined} onClick={()=>setView("cases")}>My resolution cases ({activeCases.length})</button></nav>
 {notice&&<p className="commerce-notice commerce-shell" role="status">{notice}</p>}{error&&<p className="commerce-notice commerce-error commerce-shell" role="alert">{error}</p>}
 {view==="guides"?<section className="commerce-workspace commerce-shell"><aside className="commerce-directory"><label htmlFor="commerce-search">Search by problem</label><input id="commerce-search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Refund, payment, parcel, complaint..."/>{filtered.map((guide)=><button key={guide.guideCode} type="button" className={guide.guideCode===selectedCode?"is-active":""} onClick={()=>setSelectedCode(guide.guideCode)}><span>{guide.category}</span><strong>{guide.title}</strong></button>)}</aside>
 {selected&&<article className="commerce-guide"><p className="commerce-kicker">{selected.category}</p><h2>{selected.title}</h2><p className="commerce-summary">{selected.summary}</p><div className="commerce-authority"><span>Responsible official route</span><strong>{selected.authority}</strong></div><div className="commerce-boundary"><strong>Safety boundary</strong><p>{selected.boundary}</p></div><h3>Resolution checklist</h3><ol className="commerce-preview">{selected.tasks.map((task)=><li key={task.taskId}><strong>{task.title}</strong><span>{task.description}</span></li>)}</ol><a className="commerce-official" href={selected.officialUrl} target="_blank" rel="noreferrer">Open official resolution route</a>
 <section className="commerce-builder"><h3>Save a private resolution case</h3><p>Use only nicknames or shortened references. Do not enter a full order number, address, phone, UPI ID, card or bank details, PIN, CVV, OTP, password or evidence.</p><div className="commerce-fields"><label>Seller or carrier label (optional)<input maxLength="80" value={merchantLabel} onChange={(event)=>setMerchantLabel(event.target.value)} placeholder="For example, marketplace A"/></label><label>Short order reference (optional)<input maxLength="60" value={orderLabel} onChange={(event)=>setOrderLabel(event.target.value)} placeholder="For example, ending 1234"/></label><label>Incident date<input type="date" value={incidentDate} max={today()} onChange={(event)=>setIncidentDate(event.target.value)}/></label><label>Desired outcome<select value={desiredOutcome} onChange={(event)=>setDesiredOutcome(event.target.value)}>{Object.entries(outcomeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{user?<button className="commerce-save" type="button" disabled={busy} onClick={createCase}>{busy?"Saving...":"Create resolution case"}</button>:<p className="commerce-signin">Sign in to save private progress. <Link to="/login">Sign in</Link></p>}</section></article>}</section>
 :<section className="commerce-cases commerce-shell"><p className="commerce-kicker">Owner-scoped progress</p><h2>My resolution cases</h2>{!user?<p className="commerce-empty">Sign in to view cases. <Link to="/login">Sign in</Link></p>:activeCases.length===0?<p className="commerce-empty">No active case. <button type="button" onClick={()=>setView("guides")}>Choose a route</button></p>:activeCases.map((item)=>{const completed=item.tasks.filter((task)=>task.status==="completed").length;return <article className="commerce-case" key={item.caseId}><header><div><span>{item.status} ? {outcomeLabels[item.desiredOutcome]}</span><h3>{item.guideTitle}</h3><p>{item.caseId}{item.merchantLabel?` | ${item.merchantLabel}`:""}{item.orderLabel?` | ${item.orderLabel}`:""}</p></div><strong>{completed}/{item.tasks.length}</strong></header><div className="commerce-checklist">{item.tasks.map((task)=><label key={task.taskId} className={task.status==="completed"?"is-complete":""}><input type="checkbox" checked={task.status==="completed"} disabled={busy||item.status==="resolved"} onChange={(event)=>updateTask(item,task,event.target.checked)}/><span><strong>{task.title}</strong><small>{task.description}</small></span></label>)}</div><footer><a href={item.officialUrl} target="_blank" rel="noreferrer">Continue on official route</a><div>{item.status!=="resolved"&&<button type="button" disabled={busy} onClick={()=>setStatus(item.caseId,"resolved")}>Mark resolved</button>}<button type="button" disabled={busy} onClick={()=>setStatus(item.caseId,"archived")}>Archive</button></div></footer></article>;})}</section>}</main>;
}
export default Ecommerce;
