import React,{useEffect,useState} from "react";import {Link} from "react-router-dom";import {useAuth} from "../../context/AuthContext.jsx";import api from "../../services/api.js";import "./HomeMaintenance.css";
const displayTime=(value)=>new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date(value));
function HomeMaintenance(){
 const {user}=useAuth();const [providers,setProviders]=useState([]);const [bookings,setBookings]=useState([]);const [selectedCode,setSelectedCode]=useState("");const [slots,setSlots]=useState([]);const [selectedSlot,setSelectedSlot]=useState("");const [serviceArea,setServiceArea]=useState("");const [contactPhone,setContactPhone]=useState("");const [issueSummary,setIssueSummary]=useState("");const [view,setView]=useState("book");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [error,setError]=useState("");const [cancelTarget,setCancelTarget]=useState("");
 useEffect(()=>{(async()=>{try{const requests=[api.get("/home-maintenance/providers")];if(user)requests.push(api.get("/home-maintenance/bookings/mine"));const [providerResponse,bookingResponse]=await Promise.all(requests);setProviders(providerResponse.data.providers);setBookings(bookingResponse?.data?.bookings||[]);const first=providerResponse.data.providers[0];if(first){setSelectedCode(first.providerCode);setServiceArea(first.serviceAreas[0]);}}catch(err){setError(err.response?.data?.error||"Home-service providers could not be loaded.");}})();},[user]);
 useEffect(()=>{if(!selectedCode)return;(async()=>{try{const {data}=await api.get(`/home-maintenance/providers/${selectedCode}/availability?days=7`);setSlots(data.slots);setSelectedSlot(data.slots[0]?.start||"");}catch(err){setError(err.response?.data?.error||"Availability could not be loaded.");}})();},[selectedCode]);
 const selected=providers.find(({providerCode})=>providerCode===selectedCode);const activeBookings=bookings.filter(({status})=>status==="booked");
 const chooseProvider=(provider)=>{setSelectedCode(provider.providerCode);setServiceArea(provider.serviceAreas[0]);setSelectedSlot("");setError("");};
 const book=async()=>{if(!selected||!selectedSlot)return;setBusy(true);setError("");try{const {data}=await api.post("/home-maintenance/bookings",{providerCode:selected.providerCode,startTime:selectedSlot,serviceArea,contactPhone,issueSummary});setBookings((current)=>[...current,data.booking].sort((a,b)=>new Date(a.startTime)-new Date(b.startTime)));setNotice(`Visit ${data.booking.bookingCode} booked for ${displayTime(data.booking.startTime)}.`);setView("manage");}catch(err){setError(err.response?.data?.error||"The visit could not be booked.");}finally{setBusy(false);}};
 const cancel=async(bookingCode)=>{setBusy(true);setError("");try{const {data}=await api.patch(`/home-maintenance/bookings/${bookingCode}/cancel`);setBookings((current)=>current.map((item)=>item.bookingCode===data.booking.bookingCode?data.booking:item));setNotice(`${bookingCode} cancelled.`);setCancelTarget("");}catch(err){setError(err.response?.data?.error||"The booking could not be cancelled.");}finally{setBusy(false);}};
 return <main className="home-page"><header className="home-hero"><div className="home-shell"><p className="home-kicker">Scheduled household visits</p><h1>Choose a service partner and reserve a real visit slot</h1><p>Browse a transparent demonstration catalogue, check current availability, book one slot, and manage your own visits. Replace these sample partners with verified local providers before production.</p></div></header>
 <nav className="home-tabs home-shell" aria-label="Home maintenance workspace"><button type="button" aria-current={view==="book"?"page":undefined} onClick={()=>setView("book")}>Book a visit</button><button type="button" aria-current={view==="manage"?"page":undefined} onClick={()=>setView("manage")}>My visits ({activeBookings.length})</button></nav>{notice&&<p className="home-notice home-shell" role="status">{notice}</p>}{error&&<p className="home-notice home-error home-shell" role="alert">{error}</p>}
 {view==="book"?<section className="home-booking home-shell"><aside className="home-providers"><p className="home-kicker">Demonstration partners</p><h2>Choose a service</h2>{providers.map((provider)=><button type="button" key={provider.providerCode} className={selectedCode===provider.providerCode?"is-active":""} onClick={()=>chooseProvider(provider)}><strong>{provider.service}</strong><span>{provider.name}</span><small>{provider.serviceAreas.join(" ? ")}</small></button>)}</aside>
 {selected&&<article className="home-slots"><p className="home-kicker">{selected.providerCode}</p><h2>{selected.service}</h2><p>{selected.description}</p><div className="home-partner"><span>Assigned catalogue partner</span><strong>{selected.name}</strong><small>Demonstration listing; verify provider identity and terms before production use.</small></div><h3>Available visit times</h3>{slots.length?<div className="home-slot-grid">{slots.map((slot)=><label key={slot.start} className={selectedSlot===slot.start?"is-selected":""}><input type="radio" name="visit-slot" value={slot.start} checked={selectedSlot===slot.start} onChange={()=>setSelectedSlot(slot.start)}/><span>{displayTime(slot.start)}</span></label>)}</div>:<p className="home-empty">No slots are currently available in the next seven days.</p>}
 <section className="home-details"><h3>Visit details</h3><div><label>Service area<select value={serviceArea} onChange={(event)=>setServiceArea(event.target.value)}>{selected.serviceAreas.map((area)=><option key={area}>{area}</option>)}</select></label><label>Contact phone<input value={contactPhone} onChange={(event)=>setContactPhone(event.target.value)} placeholder="Used only for this visit"/></label></div><label>Issue summary<textarea value={issueSummary} onChange={(event)=>setIssueSummary(event.target.value)} maxLength="400" placeholder="Describe the household issue without sharing access codes or unnecessary personal details"/></label>{user?<button className="home-primary" type="button" disabled={busy||!selectedSlot||contactPhone.trim().length<7||issueSummary.trim().length<5} onClick={book}>{busy?"Booking...":"Book selected visit"}</button>:<p className="home-signin">Sign in to reserve this slot. <Link to="/login">Sign in</Link></p>}</section></article>}</section>
 :<section className="home-manage home-shell"><p className="home-kicker">Owner-scoped bookings</p><h2>My home-service visits</h2>{!user?<p className="home-empty">Sign in to view visits. <Link to="/login">Sign in</Link></p>:activeBookings.length===0?<p className="home-empty">No upcoming visit. <button type="button" onClick={()=>setView("book")}>Book a visit</button></p>:activeBookings.map((item)=><article className="home-visit" key={item.bookingCode}><div className="home-visit-date"><strong>{displayTime(item.startTime)}</strong><span>Asia/Kolkata</span></div><div><p className="home-kicker">{item.bookingCode}</p><h3>{item.service}</h3><p>{item.providerName} ? {item.serviceArea}</p><small>{item.issueSummary}</small></div><div className="home-actions">{cancelTarget===item.bookingCode?<><span>Cancel this visit?</span><button type="button" disabled={busy} onClick={()=>cancel(item.bookingCode)}>Yes, cancel</button><button type="button" onClick={()=>setCancelTarget("")}>Keep visit</button></>:<button type="button" onClick={()=>setCancelTarget(item.bookingCode)}>Cancel visit</button>}</div></article>)}</section>}</main>;
}
export default HomeMaintenance;
