import React from "react";import {fireEvent,render,screen,waitFor} from "@testing-library/react";import {MemoryRouter} from "react-router-dom";import {beforeEach,describe,expect,it,vi} from "vitest";import HomeMaintenance from "./HomeMaintenance.jsx";import api from "../../services/api.js";import {useAuth} from "../../context/AuthContext.jsx";
vi.mock("../../services/api.js",()=>({default:{get:vi.fn(),post:vi.fn(),patch:vi.fn()}}));vi.mock("../../context/AuthContext.jsx",()=>({useAuth:vi.fn()}));
const provider={providerCode:"HOME-ELECTRICAL",name:"Vidhya Partner - Electrical",service:"Electrical repairs",description:"Scheduled repair visits.",serviceAreas:["Miyapur","Kukatpally"],visitMinutes:60};const slot={start:"2026-08-03T03:30:00.000Z",end:"2026-08-03T04:30:00.000Z"};const booking={bookingCode:"HOM-12AB34CD",providerCode:provider.providerCode,providerName:provider.name,service:provider.service,serviceArea:"Miyapur",contactPhone:"9876543210",issueSummary:"Switch is sparking",startTime:slot.start,endTime:slot.end,status:"booked"};
const configure=(bookings=[])=>{api.get.mockImplementation((url)=>{if(url==="/home-maintenance/providers")return Promise.resolve({data:{providers:[provider]}});if(url==="/home-maintenance/bookings/mine")return Promise.resolve({data:{bookings}});if(url.includes("/availability"))return Promise.resolve({data:{provider,slots:[slot]}});return Promise.reject(new Error(url));});api.post.mockResolvedValue({data:{booking}});api.patch.mockResolvedValue({data:{booking:{...booking,status:"cancelled"}}});};const renderPage=()=>render(<MemoryRouter><HomeMaintenance/></MemoryRouter>);
describe("Home maintenance booking",()=>{beforeEach(()=>{vi.clearAllMocks();configure();});
 it("shows real availability and clearly labels demonstration partners",async()=>{useAuth.mockReturnValue({user:null});renderPage();expect(await screen.findByRole("heading",{name:"Electrical repairs"},{timeout:5000})).toBeInTheDocument();expect(screen.getByText(/demonstration listing/i)).toBeInTheDocument();expect(await screen.findByLabelText(/3 Aug 2026/i,{},{timeout:5000})).toBeChecked();expect(screen.queryByText(/submit/i)).not.toBeInTheDocument();});
 it("books the selected provider slot with scoped visit details",async()=>{useAuth.mockReturnValue({user:{name:"Ravi"}});renderPage();await screen.findByLabelText(/3 Aug 2026/i,{},{timeout:5000});fireEvent.change(screen.getByLabelText(/contact phone/i),{target:{value:"9876543210"}});fireEvent.change(screen.getByLabelText(/issue summary/i),{target:{value:"Switch is sparking"}});fireEvent.click(screen.getByRole("button",{name:/book selected visit/i}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith("/home-maintenance/bookings",{providerCode:provider.providerCode,startTime:slot.start,serviceArea:"Miyapur",contactPhone:"9876543210",issueSummary:"Switch is sparking"}));expect(await screen.findByRole("status")).toHaveTextContent("HOM-12AB34CD");});
 it("requires confirmation before cancelling an owned visit",async()=>{useAuth.mockReturnValue({user:{name:"Ravi"}});configure([booking]);renderPage();fireEvent.click(await screen.findByRole("button",{name:/my visits/i}));fireEvent.click(screen.getByRole("button",{name:"Cancel visit"}));expect(screen.getByText(/cancel this visit/i)).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:/yes, cancel/i}));await waitFor(()=>expect(api.patch).toHaveBeenCalledWith("/home-maintenance/bookings/HOM-12AB34CD/cancel"));});
});
