import React,{useEffect,useState} from "react";import {Link} from "react-router-dom";import api from "../services/api.js";import "./Companion.css";
const goals={"access-benefit":"Find a benefit or scheme","prepare-application":"Prepare an application","resolve-problem":"Resolve a complaint or problem","book-service":"Book a local service","track-existing":"Continue or track something started","emergency-help":"Get urgent help"};
const domains={"not-sure":"I am not sure","money":"Money, banking or insurance","education":"Education","health":"Healthcare","farming":"Farming","utilities":"Electricity, telecom or LPG","shopping":"Shopping, payments or delivery","home":"Home repair","government":"Government documents or benefits","roadside":"Vehicle or roadside problem"};
const stages={student:"Student",working:"Working adult",farmer:"Farmer",caregiver:"Caregiver",senior:"Senior citizen",business:"Small business",general:"General"};
const urgency={today:"Today", "this-week":"This week",planning:"Planning ahead"};
const languages=["English","Hindi","Telugu","Tamil","Kannada","Malayalam","Marathi"];
function Companion(){const [form,setForm]=useState({goal:"access-benefit",domain:"not-sure",lifeStage:"general",urgency:"planning",language:"English",district:"",description:""});const [assessments,setAssessments]=useState([]);const [current,setCurrent]=useState(null);const [view,setView]=useState("new");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 useEffect(()=>{api.get("/companion/assessments").then(({data})=>setAssessments(data.assessments)).catch((err)=>setError(err.response?.data?.error||"Previous guidance could not be loaded."));},[]);
 const update=(field)=>(event)=>setForm((value)=>({...value,[field]:event.target.value}));
 const assess=async(event)=>{event.preventDefault();setBusy(true);setError("");setNotice("");try{const {data}=await api.post("/companion/assessments",form);setCurrent(data.assessment);setAssessments((items)=>[data.assessment,...items]);setNotice(data.safetyNotice||`Guidance ${data.assessment.assessmentId} is ready.`);}catch(err){setError(err.response?.data?.error||"Guidance could not be prepared.");}finally{setBusy(false);}};
 const archive=async(id)=>{setBusy(true);try{const {data}=await api.patch(`/companion/assessments/${id}/archive`);setAssessments((items)=>items.map((item)=>item.assessmentId===id?data.assessment:item));if(current?.assessmentId===id)setCurrent(data.assessment);setNotice(`${id} archived.`);}catch(err){setError(err.response?.data?.error||"Guidance could not be archived.");}finally{setBusy(false);}};
 const show=(assessment)=>{setCurrent(assessment);setView("new");window.scrollTo?.({top:0,behavior:"smooth"});};
 return <main className="companion-page"><header className="companion-hero"><div className="companion-shell"><p className="companion-kicker">Vidhya digital companion</p><h1>Start with your problem, not a department name</h1><p>Answer six safe questions. Vidhya Vedha ranks the most relevant task-specific journeys and explains why—without deciding eligibility or asking for identity, banking or document numbers.</p></div></header>
 <nav className="companion-tabs companion-shell" aria-label="Companion workspace"><button type="button" aria-current={view==="new"?"page":undefined} onClick={()=>setView("new")}>New guidance</button><button type="button" aria-current={view==="history"?"page":undefined} onClick={()=>setView("history")}>Previous guidance ({assessments.filter(({status})=>status==="active").length})</button></nav>{notice&&<p role="status" className="companion-notice companion-shell">{notice}</p>}{error&&<p role="alert" className="companion-notice companion-error companion-shell">{error}</p>}
 {view==="new"?<div className="companion-layout companion-shell"><form className="companion-intake" onSubmit={assess}><div><p className="companion-kicker">Guided intake</p><h2>What are you trying to achieve?</h2><p>Do not enter Aadhaar, account, application, medical-record, OTP or password details.</p></div><label>Primary goal<select value={form.goal} onChange={update("goal")}>{Object.entries(goals).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Topic<select value={form.domain} onChange={update("domain")}>{Object.entries(domains).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="companion-row"><label>Life stage<select value={form.lifeStage} onChange={update("lifeStage")}>{Object.entries(stages).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>When do you need the next step?<select value={form.urgency} onChange={update("urgency")}>{Object.entries(urgency).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div><div className="companion-row"><label>Preferred language<select value={form.language} onChange={update("language")}>{languages.map((language)=><option key={language}>{language}</option>)}</select></label><label>District label (optional)<input value={form.district} maxLength="100" onChange={update("district")} placeholder="Used only to personalise later handoffs"/></label></div><label>Describe the situation (optional)<textarea value={form.description} maxLength="500" onChange={update("description")} placeholder="For example: I am a farmer trying to understand crop insurance before the next season."/></label><button className="companion-primary" disabled={busy} type="submit">{busy?"Matching services...":"Find my best next step"}</button></form>
 <section className="companion-results" aria-live="polite"><p className="companion-kicker">Ranked guidance</p><h2>{current?"Recommended journeys":"Your matches will appear here"}</h2>{!current?<div className="companion-empty"><strong>No generic redirect</strong><p>Each result explains the fit, boundary and next actions before you open the service.</p></div>:<><div className="companion-mode"><strong>{current.mode==="openai"?"AI-ranked from reviewed services":"Reviewed rule-based matching"}</strong><span>{current.mode==="openai"?current.model:"Works without an API key"}</span></div>{current.recommendations.map((item,index)=><article className="companion-match" key={item.serviceCode}><header><span>Match {index+1} · {item.confidence} confidence</span><h3>{item.title}</h3></header><p>{item.summary}</p><div className="companion-why"><strong>Why this fits</strong><p>{item.why}</p></div><ol>{item.nextSteps.map((step)=><li key={step}>{step}</li>)}</ol><p className="companion-boundary"><strong>Boundary:</strong> {item.boundary}</p><Link to={item.route}>Open this task-specific journey</Link><Link className="companion-readiness-link" to={`/readiness?service=${item.serviceCode}&assessment=${current.assessmentId}`}>Build document-readiness checklist</Link></article>)}</>}</section></div>
 :<section className="companion-history companion-shell"><p className="companion-kicker">Owner-scoped history</p><h2>Previous guidance</h2>{assessments.length===0?<p className="companion-empty">No guidance saved yet.</p>:assessments.map((item)=><article key={item.assessmentId} className={item.status==="archived"?"is-archived":""}><div><span>{item.assessmentId} · {item.status}</span><h3>{item.recommendations[0]?.title||"Service guidance"}</h3><p>{goals[item.answers.goal]} · {domains[item.answers.domain]}</p></div><div><button type="button" onClick={()=>show(item)}>View recommendations</button>{item.status!=="archived"&&<button type="button" disabled={busy} onClick={()=>archive(item.assessmentId)}>Archive</button>}</div></article>)}</section>}</main>}
export default Companion;
