import React,{useEffect,useState} from "react";import {useSearchParams} from "react-router-dom";import api from "../services/api.js";import "./Readiness.css";
const classificationLabels={"usually-needed":"Usually needed","conditional":"Conditional","helpful":"Helpful"};const statusLabels={"not-ready":"Not ready","ready":"Ready","not-applicable":"Does not apply"};
function Readiness(){const [searchParams]=useSearchParams();const [templates,setTemplates]=useState([]);const [checklists,setChecklists]=useState([]);const [serviceCode,setServiceCode]=useState(searchParams.get("service")||"government");const [assessmentId,setAssessmentId]=useState(searchParams.get("assessment")||"");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [error,setError]=useState("");
 useEffect(()=>{Promise.all([api.get("/readiness/templates"),api.get("/readiness/checklists")]).then(([templateResponse,checklistResponse])=>{setTemplates(templateResponse.data.templates);setChecklists(checklistResponse.data.checklists);if(!searchParams.get("service")&&templateResponse.data.templates[0])setServiceCode(templateResponse.data.templates[0].serviceCode);}).catch((err)=>setError(err.response?.data?.error||"Readiness information could not be loaded."));},[searchParams]);
 const create=async(event)=>{event.preventDefault();setBusy(true);setError("");try{const payload={serviceCode};if(assessmentId)payload.assessmentId=assessmentId;const {data}=await api.post("/readiness/checklists",payload);setChecklists((items)=>[data.checklist,...items]);setNotice(`${data.checklist.checklistId} created with ${data.checklist.items.length} readiness items.`);}catch(err){setError(err.response?.data?.error||"The checklist could not be created.");}finally{setBusy(false);}};
 const updateItem=async(checklist,item,status)=>{setBusy(true);setError("");try{const {data}=await api.patch(`/readiness/checklists/${checklist.checklistId}/items/${item.itemId}`,{status});setChecklists((items)=>items.map((entry)=>entry.checklistId===data.checklist.checklistId?data.checklist:entry));if(data.checklist.status==="ready")setNotice(`${data.checklist.checklistId} is ready for official verification.`);}catch(err){setError(err.response?.data?.error||"Readiness could not be updated.");}finally{setBusy(false);}};
 const archive=async(id)=>{setBusy(true);try{const {data}=await api.patch(`/readiness/checklists/${id}/archive`);setChecklists((items)=>items.map((entry)=>entry.checklistId===id?data.checklist:entry));setNotice(`${id} archived.`);}catch(err){setError(err.response?.data?.error||"Checklist could not be archived.");}finally{setBusy(false);}};
 const active=checklists.filter(({status})=>status!=="archived");return <main className="readiness-page"><header className="readiness-hero"><div className="readiness-shell"><p className="readiness-kicker">Preparation, not document collection</p><h1>Know what to get ready before opening the official form</h1><p>Build a personalized checklist and record readiness only. Documents, identity numbers, account data and evidence remain in your own secure storage until the responsible authority asks for them.</p></div></header>{notice&&<p className="readiness-notice readiness-shell" role="status">{notice}</p>}{error&&<p className="readiness-notice readiness-error readiness-shell" role="alert">{error}</p>}
 <section className="readiness-create readiness-shell"><div><p className="readiness-kicker">Start a checklist</p><h2>Choose the journey</h2><p>?Usually needed? is preparation guidance, not an official requirement. Always verify the current authority checklist.</p></div><form onSubmit={create}><label>Service journey<select value={serviceCode} onChange={(event)=>setServiceCode(event.target.value)}>{templates.map((item)=><option value={item.serviceCode} key={item.serviceCode}>{item.title}</option>)}</select></label><label>Companion assessment (optional)<input value={assessmentId} maxLength="12" onChange={(event)=>setAssessmentId(event.target.value.toUpperCase())} placeholder="CMP-XXXXXXXX"/><span>Adds goal and life-stage preparation items.</span></label><button disabled={busy} type="submit">{busy?"Creating...":"Create readiness checklist"}</button></form></section>
 <section className="readiness-list readiness-shell"><p className="readiness-kicker">Owner-scoped preparation</p><h2>My readiness checklists</h2>{active.length===0?<p className="readiness-empty">No active checklist yet.</p>:active.map((checklist)=>{const complete=checklist.items.filter(({status})=>status==="ready"||status==="not-applicable").length;return <article className="readiness-card" key={checklist.checklistId}><header><div><span>{checklist.checklistId} ? {checklist.status}</span><h3>{checklist.serviceTitle}</h3><p>{checklist.contextSummary}</p></div><strong>{complete}/{checklist.items.length}</strong></header><div className="readiness-progress"><span style={{width:`${Math.round(complete/checklist.items.length*100)}%`}}/></div><div className="readiness-items">{checklist.items.map((item)=><section key={item.itemId} className={item.status==="ready"?"is-ready":""}><div><span>{classificationLabels[item.classification]}</span><h4>{item.title}</h4><p>{item.why}</p><small>{item.privacyNote}</small></div><label>Readiness<select aria-label={`${item.title} readiness`} value={item.status} disabled={busy} onChange={(event)=>updateItem(checklist,item,event.target.value)}>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></section>)}</div><footer><span>Verify every item against the current official source.</span><button type="button" disabled={busy} onClick={()=>archive(checklist.checklistId)}>Archive checklist</button></footer></article>})}</section></main>}
export default Readiness;
